"""Análisis de plantas PV — 97 registros con garantizado mensual."""

FULL_ANALISIS = [
  {
    'project': 'Fantasias Miguel Boca del Rio',
    'potencia_kwp': 12.2,
    'generado_kwh': 502.8,
    'garantizado': {'enero': 1068.2, 'febrero': 1190.0, 'marzo': 1618.7, 'abril': 1729.1, 'mayo': 1816.5, 'junio': 1728.2, 'julio': 1771.2, 'agosto': 1700.1, 'septiembre': 1402.7, 'octubre': 1365.6, 'noviembre': 1089.6, 'diciembre': 1000.1},
    'cumple_mayo': 'No',
    'proveedor': 'ESPAÑOLA SUMINISTROS SOLARES FOTOVOLTAICAS',
    'seguimiento': 'se subira con Francisco, para revisar una posible simulación e ingenieria',
    'fallas': 'Caida critica a las 13:00 h. Posible sombreado / afectacion severa de la tarde.',
    'responsable': 'Sergio Villalpando',
    'propuesta': 'Movimientos de paneles  de manera horizontal, se debe checcar sombra de edificios al costado',
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'Fantasias Miguel Del Valle',
    'potencia_kwp': 72.59,
    'generado_kwh': 6895.7,
    'garantizado': {'enero': 7363.4, 'febrero': 7792.1, 'marzo': 9990.6, 'abril': 9917.0, 'mayo': 9616.0, 'junio': 8171.0, 'julio': 8336.2, 'agosto': 8312.8, 'septiembre': 7544.8, 'octubre': 7512.6, 'noviembre': 7346.5, 'diciembre': 6588.6},
    'cumple_mayo': 'No',
    'proveedor': 'ESPAÑOLA SUMINISTROS SOLARES FOTOVOLTAICAS',
    'seguimiento': 'se subira con Francisco, para revisar una posible simulación e ingenieria',
    'fallas': 'Caida anticipada a las 14:35 h. Sombra urbana posible.',
    'responsable': 'Sergio Villalpando',
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'Fantasias Miguel MID Centro',
    'potencia_kwp': 42.7,
    'generado_kwh': 2010.6,
    'garantizado': {'enero': 4422.3, 'febrero': 4562.6, 'marzo': 6128.5, 'abril': 6648.9, 'mayo': 6505.8, 'junio': 6023.4, 'julio': 6636.7, 'agosto': 6237.3, 'septiembre': 5413.4, 'octubre': 4939.8, 'noviembre': 4264.6, 'diciembre': 3766.7},
    'cumple_mayo': 'No',
    'proveedor': 'ESPAÑOLA SUMINISTROS SOLARES FOTOVOLTAICAS',
    'seguimiento': 'se subira con Francisco, para revisar una posible simulación e ingenieria',
    'fallas': 'Caida marcada despues de las 15:00 h. Reduccion ~87% entre tarde y mediodia.',
    'responsable': 'Sergio Villalpando',
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'Fantasias Miguel Tlalnepantla',
    'potencia_kwp': 159.82,
    'generado_kwh': 22962.0,
    'garantizado': {'enero': 16174.8, 'febrero': 17151.7, 'marzo': 21690.5, 'abril': 21329.5, 'mayo': 21563.8, 'junio': 19012.1, 'julio': 20298.7, 'agosto': 18877.1, 'septiembre': 16683.5, 'octubre': 16817.6, 'noviembre': 15700.0, 'diciembre': 14700.7},
    'cumple_mayo': 'Si',
    'proveedor': 'BAYWA R.E. SOLAR SYSTEMS S. DE R.L. DE C.V.',
    'seguimiento': None,
    'fallas': 'Sin fallas relevantes. Caida vespertina suave desde 14:35 h.',
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 3.0,
  },
  {
    'project': 'Fantasias Miguel Coacalco',
    'potencia_kwp': 122.85,
    'generado_kwh': 7267.9,
    'garantizado': {'enero': 13991.6, 'febrero': 13991.6, 'marzo': 13991.6, 'abril': 13991.6, 'mayo': 13991.6, 'junio': 13991.6, 'julio': 13991.6, 'agosto': 13991.6, 'septiembre': 13991.6, 'octubre': 13991.6, 'noviembre': 13991.6, 'diciembre': 13991.6},
    'cumple_mayo': 'No',
    'proveedor': 'EXEL SOLAR SAPI DE CV',
    'seguimiento': 'Se tiene solucion de un inversor, se espera respuesta de esta semana del distribuidor.',
    'fallas': 'Errores de posible configuración de tensión',
    'responsable': 'Angel Stincone',
    'propuesta': 'Se revisa con fabricante por motivos de configuración',
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'Fantasias Miguel MID Campestre',
    'potencia_kwp': 163.48,
    'generado_kwh': 21296.8,
    'garantizado': {'enero': 13215.1, 'febrero': 14326.8, 'marzo': 20072.2, 'abril': 22758.3, 'mayo': 22206.4, 'junio': 20615.2, 'julio': 22748.3, 'agosto': 21261.8, 'septiembre': 18123.3, 'octubre': 15865.7, 'noviembre': 13061.2, 'diciembre': 11561.8},
    'cumple_mayo': 'No',
    'proveedor': 'ESPAÑOLA SUMINISTROS SOLARES FOTOVOLTAICAS',
    'seguimiento': None,
    'fallas': 'un deficit pequeño se analisa posible mejora,',
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'Fantasias Miguel La Tijera Palomar',
    'potencia_kwp': 195.81,
    'generado_kwh': 29349.7,
    'garantizado': {'enero': 17000.0, 'febrero': 19000.0, 'marzo': 25000.0, 'abril': 29000.0, 'mayo': 30000.0, 'junio': 26500.0, 'julio': 25500.0, 'agosto': 24000.0, 'septiembre': 22000.0, 'octubre': 20000.0, 'noviembre': 17000.0, 'diciembre': 15600.0},
    'cumple_mayo': 'Si',
    'proveedor': 'BAYWA R.E. SOLAR SYSTEMS S. DE R.L. DE C.V.',
    'seguimiento': None,
    'fallas': 'Sin fallas relevantes. Comportamiento sano todo el mes.',
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 3.0,
  },
  {
    'project': 'Fantasias Miguel San Jeronimo',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Fantasias Miguel Aguascalientes',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Fantasias Miguel MTY Centro',
    'potencia_kwp': 281.0,
    'generado_kwh': None,
    'garantizado': {'enero': 34188.3, 'febrero': 34188.3, 'marzo': 34188.3, 'abril': 34188.3, 'mayo': 34188.3, 'junio': 34188.3, 'julio': 34188.3, 'agosto': 34188.3, 'septiembre': 34188.3, 'octubre': 34188.3, 'noviembre': 34188.3, 'diciembre': 34188.3},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Fantasias Miguel QRO',
    'potencia_kwp': 102.48,
    'generado_kwh': None,
    'garantizado': {'enero': 11970.0, 'febrero': 11970.0, 'marzo': 13466.0, 'abril': 13466.0, 'mayo': 14962.0, 'junio': 13466.0, 'julio': 13466.0, 'agosto': 11970.0, 'septiembre': 11970.0, 'octubre': 11970.0, 'noviembre': 10473.0, 'diciembre': 10473.0},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'ASUR Merida',
    'potencia_kwp': 699.84,
    'generado_kwh': 1.0,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 81066.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': 'No',
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 8.0,
  },
  {
    'project': 'Aeropuerto Internacional de Ciudad Juárez',
    'potencia_kwp': 700.315,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 104286.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 8.0,
  },
  {
    'project': 'Aeropuerto Internacional de Culiacán',
    'potencia_kwp': 702.99,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 88206.3, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 8.0,
  },
  {
    'project': 'Aeropuerto Internacional de Durango',
    'potencia_kwp': 399.645,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 55415.36, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 5.0,
  },
  {
    'project': 'Aeropuerto Internacional de Torreón',
    'potencia_kwp': 704.595,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 93453.36, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 8.0,
  },
  {
    'project': 'Aeropuerto Internacional de Zacatecas',
    'potencia_kwp': 200.625,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 33836.22, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 3.0,
  },
  {
    'project': 'MERCK',
    'potencia_kwp': 336.05,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 46641.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 4.0,
  },
  {
    'project': 'Trafimar',
    'potencia_kwp': 53.46,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 7428.96, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 1.0,
  },
  {
    'project': 'EL PALACIO DE HIERRO QRO',
    'potencia_kwp': 499.95,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 82140.37, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 6.0,
  },
  {
    'project': 'Cafetal 189',
    'potencia_kwp': 231.12,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 31321.62, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 4.0,
  },
  {
    'project': 'Canela 350',
    'potencia_kwp': 115.56,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 16293.42, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 2.0,
  },
  {
    'project': 'MAESA Nave 2',
    'potencia_kwp': 466.56,
    'generado_kwh': 26045.2,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 31108.77, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': 'No',
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 8.0,
  },
  {
    'project': 'MAESA Nave 1',
    'potencia_kwp': 466.56,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 31108.77, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 8.0,
  },
  {
    'project': 'Surtidora de Lámina',
    'potencia_kwp': 57.78,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 7912.08, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SUNGROW',
    'num_inversores': 1.0,
  },
  {
    'project': 'Antea QRO - UP1 Sub#1 1500KVA',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 46273.887, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Antea QRO - UP2 Sub#2 1500KVA',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 46273.887, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'HOTEL NAVIVA',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 28810.386000000002, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Aquamatic División Del Norte',
    'potencia_kwp': 22.2,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SMA',
    'num_inversores': 2.0,
  },
  {
    'project': 'Industrias RC',
    'potencia_kwp': 186.485,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 25922.541701103113, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SMA',
    'num_inversores': 6.0,
  },
  {
    'project': 'industrias RC 2',
    'potencia_kwp': 186.485,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 25922.541701103113, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SMA',
    'num_inversores': 6.0,
  },
  {
    'project': 'Villaverde',
    'potencia_kwp': 29.16,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SMA',
    'num_inversores': 3.0,
  },
  {
    'project': 'Aquamatic Tezozomoc',
    'potencia_kwp': 44.4,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SMA',
    'num_inversores': 4.0,
  },
  {
    'project': 'Antara',
    'potencia_kwp': 136.9,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SMA',
    'num_inversores': 2.0,
  },
  {
    'project': 'Artículos Higiénicos De México SA DE CV',
    'potencia_kwp': 699.84,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': 8.0,
  },
  {
    'project': 'ASUR Merida COMEDOR',
    'potencia_kwp': 60.0,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 11704.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'ASUR Mérida-CREI',
    'potencia_kwp': 20.0,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 3211.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': 'Revisión de datos con proveedor',
    'marca_inversor': 'HUAWEI',
    'num_inversores': 1.0,
  },
  {
    'project': 'ASUR Oaxaca',
    'potencia_kwp': 697.6,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 82127.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 8.0,
  },
  {
    'project': 'FV HUAX SE1 - ASUR HUATULCO',
    'potencia_kwp': 338.0,
    'generado_kwh': 15072.2,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 48890.16, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': 'No',
    'proveedor': None,
    'seguimiento': None,
    'fallas': 'Falla de comunicación',
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'FV HUAX SE2 - ASUR HUATULCO',
    'potencia_kwp': 698.0,
    'generado_kwh': 53817.0,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 48890.16, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': 'Si',
    'proveedor': None,
    'seguimiento': None,
    'fallas': 'Falla de comunicación',
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'ASUR Tapachula',
    'potencia_kwp': 198.0,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'Fantasías Miguel Cancún',
    'potencia_kwp': 221.1,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 30687.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 3.0,
  },
  {
    'project': 'Fantasias Miguel Mariano Escobedo',
    'potencia_kwp': 699.6,
    'generado_kwh': None,
    'garantizado': {'enero': 77679.0, 'febrero': 77679.0, 'marzo': 87389.0, 'abril': 87389.0, 'mayo': 97098.0, 'junio': 87389.0, 'julio': 87389.0, 'agosto': 77679.0, 'septiembre': 77679.0, 'octubre': 77679.0, 'noviembre': 67969.0, 'diciembre': 67969.0},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 4.0,
  },
  {
    'project': 'AXIS Nave Principal',
    'potencia_kwp': 341.55,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 47404.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'TALLER FOSTER WHEELER',
    'potencia_kwp': 35.75,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 4962.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'FORMETAX FWM',
    'potencia_kwp': 187.015,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 26102.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 3.0,
  },
  {
    'project': 'MEDICA SAN ISIDRO',
    'potencia_kwp': 60.84,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 8048.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'CMT-ESPECIALIDADES',
    'potencia_kwp': 380.545,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 54170.58075, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 6.0,
  },
  {
    'project': 'FRITOS TOTIS',
    'potencia_kwp': 659.295,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 93851.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 4.0,
  },
  {
    'project': 'MEXCOAT LOTE 10',
    'potencia_kwp': 299.75,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 41602.6771875, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 4.0,
  },
  {
    'project': 'MEXCOAT LOTE 11',
    'potencia_kwp': 499.95,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 69388.68543749998, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 4.0,
  },
  {
    'project': 'Congelados Alysa',
    'potencia_kwp': 99.0,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 11134.047999999999, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'Acrilicos Sablón',
    'potencia_kwp': 638.0,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': 4.0,
  },
  {
    'project': 'Telas Bayo',
    'potencia_kwp': 121.535,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': 2.0,
  },
  {
    'project': 'IPASA BOLSAS ARTESANALES',
    'potencia_kwp': 30.51,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 4344.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'HOLOGIC COSTA RICA',
    'potencia_kwp': 399.3,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 3.0,
  },
  {
    'project': 'Autolomas SEAT',
    'potencia_kwp': 99.0,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 16435.8, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'Mil Cumbres',
    'potencia_kwp': 21.45,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'Roberto Aguilar Gasolinera',
    'potencia_kwp': 35.75,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'Hector Flores',
    'potencia_kwp': 14.55,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 1096.9992, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'Claudia Monroy - Tiro al pichón 200',
    'potencia_kwp': 6.885,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'Pablo Favela - Piamonte 1',
    'potencia_kwp': 2.43,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'Sofía Perochena - Calle del parque 30',
    'potencia_kwp': 2.025,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': 1.0,
  },
  {
    'project': 'RANCHO LA CAMPANADA',
    'potencia_kwp': 15.4,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SMA',
    'num_inversores': 2.0,
  },
  {
    'project': 'EUROVALLE',
    'potencia_kwp': 26.73,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': 1.0,
  },
  {
    'project': 'Nuvoil Grande',
    'potencia_kwp': 168.95,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 23113.0, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'Nuvoil Chico',
    'potencia_kwp': 78.48,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 11605.6, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'P18-0327',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'P18-4212',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'P18-2101',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'AGROBAL_ORDEÑA',
    'potencia_kwp': 155.89,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 22190.9415, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 2.0,
  },
  {
    'project': 'AGROBAL_ESTABLO',
    'potencia_kwp': 70.8,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 10078.38, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'SOLIS',
    'num_inversores': 1.0,
  },
  {
    'project': 'BIDASOA',
    'potencia_kwp': 2902.21,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 88206.3, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 8.0,
  },
  {
    'project': 'Guillermo Ballesteros',
    'potencia_kwp': 13.72,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 1643.1961000000001, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 2.0,
  },
  {
    'project': 'CENTRUM PARK EDIFICIO C',
    'potencia_kwp': 49.725,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 6403.32, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 1.0,
  },
  {
    'project': 'CENTRUM PARK EDIFICIO B2',
    'potencia_kwp': 179.01,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 28124.04, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 2.0,
  },
  {
    'project': 'CENTRUM PARK EDIFICIO D',
    'potencia_kwp': 52.65,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 6779.64, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 1.0,
  },
  {
    'project': 'CENTRUM PARK EDIFICIO E',
    'potencia_kwp': 167.31,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 21545.3, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 3.0,
  },
  {
    'project': 'CENTRUM PARK EDIFICIO B1',
    'potencia_kwp': 105.3,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 13559.28, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 2.0,
  },
  {
    'project': 'CENTRUM PARK EDIFICIO HVAC',
    'potencia_kwp': 616.59,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 79399.6, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 5.0,
  },
  {
    'project': 'Trimex Larry',
    'potencia_kwp': 649.8,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 91574.01, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 5.0,
  },
  {
    'project': 'CENTRO MEDICO TOLUCA',
    'potencia_kwp': 543.895,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 75796.38, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 5.0,
  },
  {
    'project': 'Hector Flores-club de golf',
    'potencia_kwp': 8.5,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 1096.9992, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 1.0,
  },
  {
    'project': 'Texturizados',
    'potencia_kwp': 212.4,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 75796.38, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 3.0,
  },
  {
    'project': 'CLARIMEX',
    'potencia_kwp': 486.16,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 68512.95, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': 'HUAWEI',
    'num_inversores': 4.0,
  },
  {
    'project': '272 Ixtepec',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 32148.6363, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': '838 Cunduacan',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 49926.0168, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'P196 Plaza Chedraui Aguascalientes Colosio',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 9588.942, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Vidanta',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': 105851.30489999999, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Notas',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Las plantas analizadas con archivo operativo de plataforma son las primeras 8 filas.',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Diferencia kWh y Diferencia % se calculan como Generado menos Garantizado (positivo = supera, negativo = deficit).',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Cumple abril = Si cuando Generado >= Garantizado del mes; No en caso contrario; N/D sin compromiso.',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': '% sugerido garantizable: porcentaje conservador posterior a mantenimiento. Verde >=90%, ambar 50-89%, rojo <50%.',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Aguascalientes: generacion disponible pero sin garantizado documentado.',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': 'Mariano Escobedo: registro mensual disponible pero sin archivos diarios de plataforma.',
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
  {
    'project': "La hoja 'Datos de generacion' conserva el desglose mensual original.",
    'potencia_kwp': None,
    'generado_kwh': None,
    'garantizado': {'enero': None, 'febrero': None, 'marzo': None, 'abril': None, 'mayo': None, 'junio': None, 'julio': None, 'agosto': None, 'septiembre': None, 'octubre': None, 'noviembre': None, 'diciembre': None},
    'cumple_mayo': None,
    'proveedor': None,
    'seguimiento': None,
    'fallas': None,
    'responsable': None,
    'propuesta': None,
    'marca_inversor': None,
    'num_inversores': None,
  },
]
