"""Catálogo completo de pólizas/plantas (244 registros del Excel oficial).

Generado automáticamente — NO editar a mano.
"""

FULL_POLIZAS = [
  {
    'item': 1,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN01-BT00101',
    'project': 'T4',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-06-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-03-28',
    'polEnd': '2033-03-28',
    'status': 'Vigente',
  },
  {
    'item': 2,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN02-BT00102',
    'project': 'T3',
    'tarifa': 'GDMTH',
    'platform': 'ON ENERGY',
    'sysStart': '2023-04-26',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-05-02',
    'polEnd': '2033-05-02',
    'status': 'Vigente',
  },
  {
    'item': 3,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN03-BT00103',
    'project': 'T2',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-08-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-05-17',
    'polEnd': '2033-05-17',
    'status': 'Vigente',
  },
  {
    'item': 4,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN04-BT00104',
    'project': 'Sala Bravo T2',
    'tarifa': 'GDMTH',
    'platform': 'ON ENERGY',
    'sysStart': '2023-06-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-05-31',
    'polEnd': '2033-05-31',
    'status': 'Vigente',
  },
  {
    'item': 5,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN05-BT00105',
    'project': 'BHS',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-07-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-03-25',
    'polEnd': '2033-03-25',
    'status': 'Vigente',
  },
  {
    'item': 6,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN06-BT00106',
    'project': 'Alpha',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-06-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-05-17',
    'polEnd': '2033-05-17',
    'status': 'Vigente',
  },
  {
    'item': 7,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN07-BT00107',
    'project': 'FBO',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-08-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-03-01',
    'polEnd': '2033-03-01',
    'status': 'Vigente',
  },
  {
    'item': 8,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN08-BT00108',
    'project': 'PTAR2',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-07-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-03-01',
    'polEnd': '2033-03-01',
    'status': 'Vigente',
  },
  {
    'item': 9,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN09-BT00109',
    'project': 'Almacén General',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-06-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-03-01',
    'polEnd': '2033-03-01',
    'status': 'Vigente',
  },
  {
    'item': 10,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN10-BT00110',
    'project': 'Comedor',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-06-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-04-21',
    'polEnd': '2033-04-21',
    'status': 'Vigente',
  },
  {
    'item': 11,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN11-BT00111',
    'project': 'Hidro',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-08-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-03-01',
    'polEnd': '2033-03-01',
    'status': 'Vigente',
  },
  {
    'item': 12,
    'grupo': 'ASUR',
    'code': 'ASRO-CUN12-BT00112',
    'project': 'T1',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-07-01',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-03-01',
    'polEnd': '2033-03-01',
    'status': 'Vigente',
  },
  {
    'item': 13,
    'grupo': 'ASUR',
    'code': 'ASRO-MID02-BT00113',
    'project': 'Mérida',
    'tarifa': 'GDMTH',
    'platform': 'ON ENERGY',
    'sysStart': '2023-08-31',
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'BESS',
    'polStart': '2023-05-02',
    'polEnd': '2033-05-02',
    'status': 'Vigente',
  },
  {
    'item': 14,
    'grupo': 'ASUR',
    'code': 'ASRO-VER03-BT00114',
    'project': 'VERACRUZ',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-07-01',
    'zona': 'Veracruz',
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2023-03-01',
    'polEnd': '2033-03-01',
    'status': 'Vigente',
  },
  {
    'item': 15,
    'grupo': 'ASUR',
    'code': 'ASRO-HUX01-BT00115',
    'project': 'HUATULCO',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-08-01',
    'zona': 'Oaxaca',
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2023-03-17',
    'polEnd': '2033-03-17',
    'status': 'Vigente',
  },
  {
    'item': 16,
    'grupo': 'ASUR',
    'code': 'ASRO-MTT01-BT00116',
    'project': 'MINATITLAN',
    'tarifa': 'GDMTH',
    'platform': 'SKYCONTROL',
    'sysStart': '2023-07-01',
    'zona': 'Veracruz',
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2023-05-10',
    'polEnd': '2033-05-10',
    'status': 'Vigente',
  },
  {
    'item': 17,
    'grupo': 'ASUR',
    'code': 'ASRO-HUX02-FV00117',
    'project': 'FV HUAX SE1',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-07-07',
    'zona': 'Oaxaca',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2024-07-07',
    'polEnd': '2034-07-07',
    'status': 'Vigente',
  },
  {
    'item': 18,
    'grupo': 'ASUR',
    'code': 'ASRO-HUX03-FV00118',
    'project': 'FV HUAX SE2',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-07-07',
    'zona': 'Oaxaca',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2024-07-07',
    'polEnd': '2034-07-07',
    'status': 'Vigente',
  },
  {
    'item': 19,
    'grupo': 'ASUR',
    'code': 'ASRO-MID03-FV00119',
    'project': 'ASUR Mérida',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2022-08-19',
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': '2 completos, 2 limpiezas',
    'polStart': '2022-08-19',
    'polEnd': '2032-08-19',
    'status': 'Vigente',
  },
  {
    'item': 20,
    'grupo': 'ASUR',
    'code': 'ASRO-OAX01-FV00120',
    'project': 'ASUR Oaxaca',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2023-02-03',
    'zona': 'Oaxaca',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2023-02-02',
    'polEnd': '2033-02-02',
    'status': 'Vigente',
  },
  {
    'item': 21,
    'grupo': 'ASUR',
    'code': 'ASRO-TAP01-FV00121',
    'project': 'ASUR Tapachula',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-05-22',
    'zona': 'Chiapas',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2024-05-22',
    'polEnd': '2034-05-22',
    'status': 'Vigente',
  },
  {
    'item': 22,
    'grupo': 'ASUR',
    'code': 'ASRO-MID12-FV00122',
    'project': 'ASUR Mérida-Comedor',
    'tarifa': 'GDMTO',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': '2 completos, 2 limpiezas',
    'polStart': '2025-09-01',
    'polEnd': '2035-09-01',
    'status': 'Vigente',
  },
  {
    'item': 23,
    'grupo': 'ASUR',
    'code': 'ASRO-MID13-FV00123',
    'project': 'ASUR Mérida-CREI',
    'tarifa': 'GDMTO',
    'platform': 'Solis',
    'sysStart': '2025-07-27',
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': '2 completos, 2 limpiezas',
    'polStart': '2025-09-01',
    'polEnd': '2035-09-01',
    'status': 'Vigente',
  },
  {
    'item': 24,
    'grupo': 'OMA',
    'code': 'OMAO-CUL01-BT00201',
    'project': 'CULIACAN',
    'tarifa': None,
    'platform': None,
    'sysStart': '2021-11-17',
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2021-11-30',
    'polEnd': '2031-11-30',
    'status': 'Vigente',
  },
  {
    'item': 25,
    'grupo': 'OMA',
    'code': 'OMAO-MTY01-BT00202',
    'project': 'MONTERREY',
    'tarifa': None,
    'platform': None,
    'sysStart': '2022-12-21',
    'zona': 'Nuevo León',
    'cuadrilla': 'Monterrey',
    'poliza': 'BESS',
    'polStart': '2022-10-01',
    'polEnd': '2032-10-01',
    'status': 'Vigente',
  },
  {
    'item': 26,
    'grupo': 'OMA',
    'code': 'OMAO-ACA01-BT00203',
    'project': 'ACAPULCO',
    'tarifa': None,
    'platform': None,
    'sysStart': '2023-01-23',
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2023-02-01',
    'polEnd': '2033-02-01',
    'status': 'Vigente',
  },
  {
    'item': 27,
    'grupo': 'OMA',
    'code': 'OMAO-CJS01-BT00204',
    'project': 'JUAREZ',
    'tarifa': None,
    'platform': None,
    'sysStart': '2023-04-20',
    'zona': 'Cd. Juárez',
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2023-05-02',
    'polEnd': '2033-05-02',
    'status': 'Vigente',
  },
  {
    'item': 28,
    'grupo': 'OMA',
    'code': 'OMAO-CUU01-BT00205',
    'project': 'CHIHUAHUA CHICO',
    'tarifa': None,
    'platform': None,
    'sysStart': '2022-12-01',
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2022-12-18',
    'polEnd': '2032-12-18',
    'status': 'Vigente',
  },
  {
    'item': 29,
    'grupo': 'OMA',
    'code': 'OMAO-CUU02-BT00206',
    'project': 'CHIHUAHUA GRANDE',
    'tarifa': None,
    'platform': None,
    'sysStart': '2023-08-15',
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2022-12-01',
    'polEnd': '2032-12-01',
    'status': 'Vigente',
  },
  {
    'item': 30,
    'grupo': 'OMA',
    'code': 'OMAO-ZIH01-BT00207',
    'project': 'ZIHUATANEJO',
    'tarifa': None,
    'platform': None,
    'sysStart': '2023-09-01',
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2023-08-26',
    'polEnd': '2033-08-26',
    'status': 'Vigente',
  },
  {
    'item': 31,
    'grupo': 'OMA',
    'code': 'OMAO-REX01-BT00208',
    'project': 'REYNOSA',
    'tarifa': None,
    'platform': None,
    'sysStart': '2023-04-19',
    'zona': None,
    'cuadrilla': 'Monterrey',
    'poliza': 'BESS',
    'polStart': '2023-09-01',
    'polEnd': '2033-09-01',
    'status': 'Vigente',
  },
  {
    'item': 32,
    'grupo': 'OMA',
    'code': 'OMAO-TRC01-BT00209',
    'project': 'TORREÓN',
    'tarifa': None,
    'platform': None,
    'sysStart': '2023-04-01',
    'zona': 'Torreón',
    'cuadrilla': 'Monterrey',
    'poliza': 'BESS',
    'polStart': '2023-05-29',
    'polEnd': '2033-05-29',
    'status': 'Vigente',
  },
  {
    'item': 33,
    'grupo': 'OMA',
    'code': 'OMAO-DGO01-BT00210',
    'project': 'DURANGO',
    'tarifa': None,
    'platform': None,
    'sysStart': '2023-05-01',
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2023-05-06',
    'polEnd': '2033-05-06',
    'status': 'Vigente',
  },
  {
    'item': 34,
    'grupo': 'OMA',
    'code': 'OMAO-ZAC01-BT00211',
    'project': 'ZACATECAS',
    'tarifa': None,
    'platform': None,
    'sysStart': '2023-05-01',
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2023-05-16',
    'polEnd': '2033-05-16',
    'status': 'Vigente',
  },
  {
    'item': 35,
    'grupo': 'OMA',
    'code': 'OMAO-DGO02-FV00212',
    'project': 'Aeropuerto Internacional de Durango',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-09-29',
    'zona': 'Durango',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2021-09-29',
    'polEnd': '2031-09-21',
    'status': 'Vigente',
  },
  {
    'item': 36,
    'grupo': 'OMA',
    'code': 'OMAO-TRC02-FV00213',
    'project': 'Aeropuerto Internacional de Torreón',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-10-07',
    'zona': 'Coahuila',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2021-10-07',
    'polEnd': '2031-10-07',
    'status': 'Vigente',
  },
  {
    'item': 37,
    'grupo': 'OMA',
    'code': 'OMAO-ZAC02-FV00214',
    'project': 'Aeropuerto Internacional de Zacatecas',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-10-11',
    'zona': 'Zacatecas',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2021-10-11',
    'polEnd': '2031-10-11',
    'status': 'Vigente',
  },
  {
    'item': 38,
    'grupo': 'OMA',
    'code': 'OMAO-CUL02-FV00215',
    'project': 'Aeropuerto Internacional de Culiacán',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-10-18',
    'zona': 'Culiacán',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2021-10-18',
    'polEnd': '2031-10-18',
    'status': 'Vigente',
  },
  {
    'item': 39,
    'grupo': 'OMA',
    'code': 'OMAO-CJS02-FV00216',
    'project': 'Aeropuerto Internacional de Ciudad Juárez',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-12-04',
    'zona': 'Chihuahua',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2021-12-04',
    'polEnd': '2031-12-21',
    'status': 'Vigente',
  },
  {
    'item': 40,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-EDO13-FV00301',
    'project': 'Fantasías Miguel Tultitlan',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-04-09',
    'zona': 'Estado de México',
    'cuadrilla': 'Tizayuca',
    'poliza': 'ELÉCTRICO',
    'polStart': '2024-04-09',
    'polEnd': '2025-04-09',
    'status': 'Vencida',
  },
  {
    'item': 41,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-MID09-FV00302',
    'project': 'Fantasías Miguel Cancún',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-02-04',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'ELÉCTRICO',
    'polStart': '2024-02-04',
    'polEnd': '2026-02-04',
    'status': 'Vencida',
  },
  {
    'item': 42,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-CMX29-FV00303',
    'project': 'Fantasías Miguel Mariano Escobedo',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-06-06',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'ELÉCTRICO',
    'polStart': '2024-06-06',
    'polEnd': '2026-06-06',
    'status': 'Vigente',
  },
  {
    'item': 43,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-AGS02-FV00304',
    'project': 'Aguascalientes',
    'tarifa': None,
    'platform': None,
    'sysStart': '2026-03-01',
    'zona': 'Aguascalientes',
    'cuadrilla': 'Especial',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': '2026-03-01',
    'polEnd': '2027-03-01',
    'status': 'Vigente',
  },
  {
    'item': 44,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-CMX30-FV00305',
    'project': 'CDMX Uruguay',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 45,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-CMX31-FV00306',
    'project': 'Coapa',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 46,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-CMX32-FV00307',
    'project': 'Coyoacan',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 47,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-CMX33-FV00308',
    'project': 'Del Valle',
    'tarifa': 'GDBT',
    'platform': 'Solis',
    'sysStart': '2025-11-05',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-11-05',
    'polEnd': '2026-11-05',
    'status': 'Vigente',
  },
  {
    'item': 48,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-GDL02-FV00309',
    'project': 'GDL Patria',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 49,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-EDO14-FV00310',
    'project': 'Interlomas',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 50,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-JAL01-FV00311',
    'project': 'JAL - La Tijera Palomar',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2025-12-08',
    'zona': 'Guadalajara',
    'cuadrilla': 'Especial',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-12-08',
    'polEnd': '2026-12-08',
    'status': 'Vigente',
  },
  {
    'item': 51,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-EDO15-FV00312',
    'project': 'Metepec',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 52,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-MID10-FV00313',
    'project': 'MID Campestre',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2026-02-20',
    'zona': None,
    'cuadrilla': 'Península',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': '2026-01-20',
    'polEnd': '2027-01-20',
    'status': 'Vigente',
  },
  {
    'item': 53,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-MID11-FV00314',
    'project': 'MID Centro',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2026-01-13',
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'GENERACIÓN',
    'polStart': '2026-01-13',
    'polEnd': '2027-01-13',
    'status': 'Vigente',
  },
  {
    'item': 54,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-MTY02-FV00315',
    'project': 'MTY 1 -Garza Sada',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Nuevo León',
    'cuadrilla': 'Monterrey',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 55,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-MTY03-FV00316',
    'project': 'MTY 2 -San Jerónimo',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Nuevo León',
    'cuadrilla': 'Monterrey',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 56,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-MTY04-FV00317',
    'project': 'MTY - Centro',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Nuevo León',
    'cuadrilla': 'Monterrey',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 57,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-MTY05-FV00318',
    'project': 'MTY Citadel',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Nuevo León',
    'cuadrilla': 'Monterrey',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 58,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-EDO16-FV00319',
    'project': 'Naucalpan Satelite',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 59,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-EDO17-FV00320',
    'project': 'Pedregal',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 60,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-PUE03-FV00321',
    'project': 'Puebla',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Puebla',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 61,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-QRO02-FV00322',
    'project': 'QRO Arboledas',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2025-12-09',
    'zona': 'Querétaro',
    'cuadrilla': 'Especial',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-12-09',
    'polEnd': '2026-12-09',
    'status': 'Vigente',
  },
  {
    'item': 62,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-EDO18-FV00323',
    'project': 'San Francisco COACALCO',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 63,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-EDO19-FV00324',
    'project': 'Tlalnepantla',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2025-10-30',
    'zona': 'Estado de México',
    'cuadrilla': 'Tizayuca',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-10-30',
    'polEnd': '2026-10-30',
    'status': 'Vigente',
  },
  {
    'item': 64,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-TRC03-FV00325',
    'project': 'Torreón',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Torreón',
    'cuadrilla': 'Monterrey',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 65,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-VER04-HB00326',
    'project': 'Ver - Bca del Rio',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-06-01',
    'polEnd': '2026-06-01',
    'status': 'Vigente',
  },
  {
    'item': 66,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-CMX34-FV00327',
    'project': 'Xochimilco',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 67,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-CJS03-FV00328',
    'project': 'Ciudad Juarez',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 68,
    'grupo': 'Fantasías Miguel',
    'code': 'FTMO-PUE04-FV00329',
    'project': 'Puebla 2',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Puebla',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 69,
    'grupo': 'Agencias Península',
    'code': 'APEO-MID04-FV00401',
    'project': 'KIA PENINSULA MÉRIDA',
    'tarifa': 'GDMTH',
    'platform': 'EnnexOS',
    'sysStart': '2019-10-16',
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2019-10-16',
    'polEnd': '2025-05-05',
    'status': 'Vencida',
  },
  {
    'item': 70,
    'grupo': 'Agencias Península',
    'code': 'APEO-MID05-FV00402',
    'project': 'MG Peninsula Mérida',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-12-31',
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2021-12-31',
    'polEnd': '2025-05-05',
    'status': 'Vencida',
  },
  {
    'item': 71,
    'grupo': 'Agencias Península',
    'code': 'APEO-CUN13-FV00403',
    'project': 'HONDA CARIBE',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-12-30',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2021-12-30',
    'polEnd': '2025-05-05',
    'status': 'Vencida',
  },
  {
    'item': 72,
    'grupo': 'Agencias Península',
    'code': 'APEO-CUN14-FV00404',
    'project': 'MG BONAMPAK',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-12-30',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2021-12-30',
    'polEnd': '2025-05-05',
    'status': 'Vencida',
  },
  {
    'item': 73,
    'grupo': 'Agencias Península',
    'code': 'APEO-CUN15-FV00405',
    'project': 'KIA Bonampak',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-12-29',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2021-12-29',
    'polEnd': '2025-05-05',
    'status': 'Vencida',
  },
  {
    'item': 74,
    'grupo': 'Agencias Península',
    'code': 'APEO-CUN16-FV00406',
    'project': 'Honda Laguna Chetumal',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2023-01-22',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2023-01-22',
    'polEnd': '2025-05-05',
    'status': 'Vencida',
  },
  {
    'item': 75,
    'grupo': 'Agencias Península',
    'code': 'APEO-MID06-FV00407',
    'project': 'Honda Montejo',
    'tarifa': 'GDMTO',
    'platform': 'EnnexOS',
    'sysStart': '2020-03-31',
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2020-03-31',
    'polEnd': '2025-05-05',
    'status': 'Vencida',
  },
  {
    'item': 76,
    'grupo': 'Agencias Península',
    'code': 'APEO-MID07-FV00408',
    'project': 'Honda Montecristo',
    'tarifa': 'GDMTO',
    'platform': 'EnnexOS',
    'sysStart': '2019-07-30',
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2019-07-30',
    'polEnd': '2025-05-05',
    'status': 'Vencida',
  },
  {
    'item': 77,
    'grupo': 'Agencias Península',
    'code': 'APEO-MID08-FV00409',
    'project': 'Honda Circuito',
    'tarifa': 'GDMTO',
    'platform': 'EnnexOS',
    'sysStart': '2020-03-27',
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2020-03-27',
    'polEnd': '2025-05-05',
    'status': 'Vencida',
  },
  {
    'item': 78,
    'grupo': 'Agencias Península',
    'code': 'APEO-PCM01-FV00410',
    'project': 'Honda Playa Del Carmen',
    'tarifa': 'GDMTO',
    'platform': 'SunGrow',
    'sysStart': '2021-12-29',
    'zona': 'Quintana Roo',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2021-12-29',
    'polEnd': '2025-05-05',
    'status': 'Vencida',
  },
  {
    'item': 79,
    'grupo': 'Grupo Cruz',
    'code': 'GCRO-CMX35-FV00501',
    'project': 'INDUSTRIAS RC',
    'tarifa': 'GDMTH',
    'platform': 'EnnexOS',
    'sysStart': '2019-01-31',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'INCIDENCIAS FULL',
    'polStart': '2019-01-31',
    'polEnd': '2021-11-30',
    'status': 'Vencida',
  },
  {
    'item': 80,
    'grupo': 'Grupo Cruz',
    'code': 'GCRO-CMX36-FV00502',
    'project': 'Cafetal 189',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-07-22',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'INCIDENCIAS FULL',
    'polStart': '2021-07-22',
    'polEnd': '2022-07-22',
    'status': 'Vencida',
  },
  {
    'item': 81,
    'grupo': 'Grupo Cruz',
    'code': 'GCRO-CMX37-FV00503',
    'project': 'Canela 350',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2024-01-01',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'INCIDENCIAS FULL',
    'polStart': '2024-01-01',
    'polEnd': '2024-02-01',
    'status': 'Vencida',
  },
  {
    'item': 82,
    'grupo': 'Grupo Cruz',
    'code': 'GCRO-CMX38-FV00504',
    'project': 'MAESA Nave 2',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-09-02',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'INCIDENCIAS FULL',
    'polStart': '2021-09-02',
    'polEnd': '2022-09-02',
    'status': 'Vencida',
  },
  {
    'item': 84,
    'grupo': 'Grupo Cruz',
    'code': 'GCRO-EDO20-FV00505',
    'project': 'Surtidora de Lámina',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-07-12',
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'INCIDENCIAS FULL',
    'polStart': '2021-07-12',
    'polEnd': '2022-07-12',
    'status': 'Vencida',
  },
  {
    'item': 85,
    'grupo': 'Energía Real',
    'code': 'ENRO-HGO07-FV00601',
    'project': 'Muebles Dixy',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': '2024-08-01',
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'FINALIZADO',
    'polStart': '2024-08-01',
    'polEnd': '2025-08-01',
    'status': 'Vencida',
  },
  {
    'item': 86,
    'grupo': 'Kiwa',
    'code': 'KIWO-GTO01-BT00701',
    'project': 'Kiwa BESS Guanajuato',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Guanajuato',
    'cuadrilla': 'Especial',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 87,
    'grupo': 'Kiwa',
    'code': 'KIWO-EDO21-BT00702',
    'project': 'Kiwa BESS Valle de Bravo',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 88,
    'grupo': 'Kiwa',
    'code': 'INDO-GTO02-FV05093',
    'project': 'Saga Irapuato',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Guanajuato',
    'cuadrilla': 'Especial',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 89,
    'grupo': 'Foster Wheeler',
    'code': 'FOSO-HGO08-FV00801',
    'project': 'Formetax',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-10-01',
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'COMPLETO',
    'polStart': '2024-10-01',
    'polEnd': '2027-10-01',
    'status': 'Vigente',
  },
  {
    'item': 90,
    'grupo': 'Foster Wheeler',
    'code': 'FOSO-HGO09-FV00802',
    'project': 'Taller Foster Wheeler',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-10-01',
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'COMPLETO',
    'polStart': '2024-10-01',
    'polEnd': '2027-10-01',
    'status': 'Vigente',
  },
  {
    'item': 91,
    'grupo': 'Foster Wheeler',
    'code': 'FOSO-HGO10-FV00803',
    'project': 'Axis Nave Principal',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-10-01',
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'COMPLETO',
    'polStart': '2024-10-01',
    'polEnd': '2027-10-01',
    'status': 'Vigente',
  },
  {
    'item': 92,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC02-FV00901',
    'project': 'Roble',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 93,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC03-FV00902',
    'project': 'Cuzama',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 94,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC04-FV00903',
    'project': 'Rep Ligera',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 95,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC05-FV00904',
    'project': 'St Rita',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 96,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC06-FV00905',
    'project': 'Cartonera',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 97,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC07-FV00906',
    'project': 'Incubadora',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 98,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC08-FV00907',
    'project': 'Planta Alimentos',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 99,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC09-FV00908',
    'project': 'Oficinas 65',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 100,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC10-FV00909',
    'project': 'Sta Cruz 1',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 101,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC11-FV00910',
    'project': 'Sta Cruz 2',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 102,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC12-FV00911',
    'project': 'Acopio',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 103,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC13-FV00912',
    'project': 'Empacadora',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 104,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC14-FV00913',
    'project': 'Pasteurizadora',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 105,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC15-FV00914',
    'project': 'Petectunich',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 106,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC16-FV00915',
    'project': 'Sn. Gregorio',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 107,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC17-FV00916',
    'project': 'Lepan 2',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 108,
    'grupo': 'Kaki',
    'code': 'KAKO-YUC18-FV00917',
    'project': 'Lepan 1',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2025-04-01',
    'polEnd': '2026-04-01',
    'status': 'Vencida',
  },
  {
    'item': 109,
    'grupo': 'Corcimex',
    'code': 'CORO-TLX01-FV01101',
    'project': 'Facomex',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': None,
    'zona': 'Tlaxcala',
    'cuadrilla': 'Especial',
    'poliza': 'FINALIZADO',
    'polStart': '2021-10-16',
    'polEnd': '2023-10-23',
    'status': 'Vencida',
  },
  {
    'item': 110,
    'grupo': 'Corcimex',
    'code': 'CORO-TLX02-FV01102',
    'project': 'Santa Susana',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Tlaxcala',
    'cuadrilla': 'Especial',
    'poliza': 'FINALIZADO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 111,
    'grupo': 'Supervisa',
    'code': 'SUPO-CMX44-FV01201',
    'project': 'SUPERVISA BOMSOR',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'NULO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 112,
    'grupo': 'Supervisa',
    'code': 'SUPO-CMX45-FV01202',
    'project': 'SUPERVISA INGENIAL',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'NULO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 113,
    'grupo': 'Supervisa',
    'code': 'SUPO-CMX46-FV01203',
    'project': 'SUPERVISA JCB',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'NULO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 114,
    'grupo': 'Supervisa',
    'code': 'SUPO-CMX47-FV01204',
    'project': 'SUPERVISA SUPERTECNICOS',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'NULO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 115,
    'grupo': 'Supervisa',
    'code': 'SUPO-CMX50-FV01205',
    'project': 'SUPERVISA REVOLUCIÓN',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'NULO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 116,
    'grupo': 'Centro Médico',
    'code': 'MEDO-EDO24-FV01301',
    'project': 'CENTRO MEDICO TOLUCA',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': '2025-06-01',
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2025-05-01',
    'polEnd': '2027-05-01',
    'status': 'Vigente',
  },
  {
    'item': 117,
    'grupo': 'Centro Médico',
    'code': 'MEDO-EDO25-FV01302',
    'project': 'MEDICA SAN ISIDRO',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2025-04-26',
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2025-05-01',
    'polEnd': '2027-06-13',
    'status': 'Vigente',
  },
  {
    'item': 118,
    'grupo': 'Centro Médico',
    'code': 'MEDO-EDO26-FV01303',
    'project': 'CENTRO MEDICO ESPECIALIDADES',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2025-05-16',
    'zona': 'Hidalgo',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2025-06-19',
    'polEnd': '2027-06-19',
    'status': 'Vigente',
  },
  {
    'item': 119,
    'grupo': 'SKY FUND',
    'code': 'PRKO-EDO27-FV01401',
    'project': 'CENTRUM PARK EDIFICIO B1',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-07-01',
    'polEnd': '2026-07-01',
    'status': 'Vigente',
  },
  {
    'item': 120,
    'grupo': 'SKY FUND',
    'code': 'PRKO-EDO28-FV01402',
    'project': 'CENTRUM PARK EDIFICIO HVAC',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-07-01',
    'polEnd': '2026-07-01',
    'status': 'Vigente',
  },
  {
    'item': 121,
    'grupo': 'SKY FUND',
    'code': 'PRKO-EDO29-FV01403',
    'project': 'CENTRUM PARK EDIFICIO B2',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-07-01',
    'polEnd': '2026-07-01',
    'status': 'Vigente',
  },
  {
    'item': 122,
    'grupo': 'SKY FUND',
    'code': 'PRKO-EDO30-FV01404',
    'project': 'CENTRUM PARK EDIFICIO C',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-07-01',
    'polEnd': '2026-07-01',
    'status': 'Vigente',
  },
  {
    'item': 123,
    'grupo': 'SKY FUND',
    'code': 'PRKO-EDO31-FV01405',
    'project': 'CENTRUMPARK EDIFICIO D',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-07-01',
    'polEnd': '2026-07-01',
    'status': 'Vigente',
  },
  {
    'item': 124,
    'grupo': 'SKY FUND',
    'code': 'PRKO-EDO32-FV01406',
    'project': 'CENTRUM PARK EDIFICIO E',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'GENERACIÓN',
    'polStart': '2025-07-01',
    'polEnd': '2026-07-01',
    'status': 'Vigente',
  },
  {
    'item': 125,
    'grupo': 'Indep.',
    'code': 'INDO-HGO01-HB05001',
    'project': 'ALYSA',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-02-15',
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'COMPLETO',
    'polStart': '2024-05-01',
    'polEnd': '2034-05-01',
    'status': 'Vigente',
  },
  {
    'item': 126,
    'grupo': 'Indep.',
    'code': 'INDO-AGS01-BT05002',
    'project': 'DISEKO',
    'tarifa': None,
    'platform': None,
    'sysStart': '2022-12-01',
    'zona': 'Aguascalientes',
    'cuadrilla': 'Especial',
    'poliza': 'BESS',
    'polStart': '2023-07-31',
    'polEnd': '2033-07-31',
    'status': 'Vigente',
  },
  {
    'item': 127,
    'grupo': 'Indep.',
    'code': 'INDO-CMX01-HB05003',
    'project': 'VITROGENERA',
    'tarifa': None,
    'platform': None,
    'sysStart': '2024-05-01',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2024-05-01',
    'polEnd': '2034-05-01',
    'status': 'Vigente',
  },
  {
    'item': 128,
    'grupo': 'Indep.',
    'code': 'INDO-CMX02-BT05004',
    'project': 'BOCAR',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'BESS',
    'polStart': '2024-08-01',
    'polEnd': '2025-08-01',
    'status': 'Vencida',
  },
  {
    'item': 129,
    'grupo': 'Indep.',
    'code': 'INDO-NLE01-BT05005',
    'project': 'REGIOPET',
    'tarifa': None,
    'platform': None,
    'sysStart': '2024-09-02',
    'zona': 'Nuevo León',
    'cuadrilla': 'Monterrey',
    'poliza': 'GESTIÓN DE ACTIVOS',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 130,
    'grupo': 'Indep.',
    'code': 'INDO-PUE01-BT05006',
    'project': 'TELAS ASTURCON',
    'tarifa': None,
    'platform': None,
    'sysStart': '2025-12-01',
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'FINALIZADO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 131,
    'grupo': 'Indep.',
    'code': 'INDO-EDO01-FV05007',
    'project': 'Artículos Higiénicos De México SA DE CV',
    'tarifa': 'GDMTH',
    'platform': 'EnnexOS',
    'sysStart': '2020-12-17',
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'ELÉCTRICO',
    'polStart': '2020-12-17',
    'polEnd': '2022-12-17',
    'status': 'Vencida',
  },
  {
    'item': 132,
    'grupo': 'Indep.',
    'code': 'INDO-HGO02-FV05008',
    'project': 'MEXCOAT LOTE 10',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-05-11',
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'COMPLETO',
    'polStart': '2024-05-11',
    'polEnd': '2026-05-11',
    'status': 'Vencida',
  },
  {
    'item': 133,
    'grupo': 'Indep.',
    'code': 'INDO-HGO03-FV05009',
    'project': 'MEXCOAT LOTE 11',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2024-05-14',
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'COMPLETO',
    'polStart': '2024-05-14',
    'polEnd': '2026-05-14',
    'status': 'Vencida',
  },
  {
    'item': 134,
    'grupo': 'Indep.',
    'code': 'INDO-EDO02-FV05010',
    'project': 'Autotransportes ZONTE',
    'tarifa': 'GDMTO',
    'platform': 'SunGrow',
    'sysStart': '2021-06-25',
    'zona': 'Estado de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2021-06-25',
    'polEnd': '2024-06-22',
    'status': 'Vencida',
  },
  {
    'item': 135,
    'grupo': 'Indep.',
    'code': 'INDO-CMX03-FV05011',
    'project': 'Autolomas SEAT',
    'tarifa': 'GDMTO',
    'platform': 'Solis',
    'sysStart': '2025-01-30',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2024-11-11',
    'polEnd': '2025-11-11',
    'status': 'Vencida',
  },
  {
    'item': 136,
    'grupo': 'Indep.',
    'code': 'INDO-EDO03-FV05012',
    'project': 'Trafimar',
    'tarifa': 'GDBT',
    'platform': 'SunGrow',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2022-08-02',
    'polEnd': '2025-08-01',
    'status': 'Vencida',
  },
  {
    'item': 137,
    'grupo': 'Indep.',
    'code': 'INDO-CMX04-FV05013',
    'project': 'Mil Cumbres',
    'tarifa': 'GDBT',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'COMPLETO',
    'polStart': '2024-02-26',
    'polEnd': '2025-02-26',
    'status': 'Vencida',
  },
  {
    'item': 138,
    'grupo': 'Indep.',
    'code': 'INDO-HGO04-FV05014',
    'project': 'Roberto Aguilar Gasolinera',
    'tarifa': 'GDBT',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'COMPLETO',
    'polStart': '2023-08-31',
    'polEnd': '2026-08-31',
    'status': 'Vigente',
  },
  {
    'item': 139,
    'grupo': 'Indep.',
    'code': 'INDO-CMX05-FV05015',
    'project': 'AQUAMATIC TEZOZÓMOC',
    'tarifa': 'GDBT',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2019-09-11',
    'polEnd': '2021-09-11',
    'status': 'Vencida',
  },
  {
    'item': 140,
    'grupo': 'Indep.',
    'code': 'INDO-QRO01-FV05016',
    'project': 'Interaqua Qro',
    'tarifa': 'PDBT',
    'platform': 'Solis',
    'sysStart': '2022-01-01',
    'zona': 'Querétaro',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2022-01-01',
    'polEnd': '2023-01-01',
    'status': 'Vencida',
  },
  {
    'item': 141,
    'grupo': 'Indep.',
    'code': 'INDO-EDO04-FV05017',
    'project': 'Aquamatic División Del Norte',
    'tarifa': 'PDBT',
    'platform': 'EnnexOS',
    'sysStart': '2019-04-24',
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2019-04-24',
    'polEnd': '2021-04-19',
    'status': 'Vencida',
  },
  {
    'item': 142,
    'grupo': 'Indep.',
    'code': 'INDO-CMX06-FV05018',
    'project': 'Aquamatic Calzada Del Hueso',
    'tarifa': 'PDBT',
    'platform': 'EnnexOS',
    'sysStart': '2019-04-24',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2019-04-24',
    'polEnd': '2021-04-24',
    'status': 'Vencida',
  },
  {
    'item': 143,
    'grupo': 'Indep.',
    'code': 'INDO-EDO05-FV05019',
    'project': 'Bernardo Quintana',
    'tarifa': 'PDBT',
    'platform': 'EnnexOS',
    'sysStart': '2020-08-28',
    'zona': 'Estado de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2020-08-28',
    'polEnd': '2021-08-27',
    'status': 'Vencida',
  },
  {
    'item': 144,
    'grupo': 'Indep.',
    'code': 'INDO-MID01-FV05020',
    'project': 'Villa Verde',
    'tarifa': 'PDBT',
    'platform': 'EnnexOS',
    'sysStart': '2020-10-12',
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'COMPLETO',
    'polStart': '2020-10-12',
    'polEnd': '2025-09-17',
    'status': 'Vencida',
  },
  {
    'item': 145,
    'grupo': 'Indep.',
    'code': 'INDO-CMX07-FV05021',
    'project': 'Interaqua 2',
    'tarifa': 'PDBT',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2018-12-21',
    'polEnd': '2019-12-21',
    'status': 'Vencida',
  },
  {
    'item': 146,
    'grupo': 'Indep.',
    'code': 'INDO-CMX08-FV05022',
    'project': 'Interaqua 1',
    'tarifa': 'PDBT',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2018-12-27',
    'polEnd': '2019-12-27',
    'status': 'Vencida',
  },
  {
    'item': 147,
    'grupo': 'Indep.',
    'code': 'INDO-CMX09-FV05023',
    'project': 'Sergio Vela - Cedral',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2024-02-26',
    'polEnd': '2025-02-24',
    'status': 'Vencida',
  },
  {
    'item': 148,
    'grupo': 'Indep.',
    'code': 'INDO-CMX10-FV05024',
    'project': 'Rafael Villalobos - Loma del rey 50',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2020-11-18',
    'polEnd': '2021-11-18',
    'status': 'Vencida',
  },
  {
    'item': 149,
    'grupo': 'Indep.',
    'code': 'INDO-EDO06-FV05025',
    'project': 'Eduardo Arcila',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2020-07-31',
    'polEnd': '2025-02-13',
    'status': 'Vencida',
  },
  {
    'item': 150,
    'grupo': 'Indep.',
    'code': 'INDO-CMX11-FV05026',
    'project': 'Miguel Irurita - Bosque alto 8',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2024-02-01',
    'polEnd': '2025-02-01',
    'status': 'Vencida',
  },
  {
    'item': 151,
    'grupo': 'Indep.',
    'code': 'INDO-EDO07-FV05027',
    'project': 'Familia Treviño',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2021-03-11',
    'polEnd': '2025-01-08',
    'status': 'Vencida',
  },
  {
    'item': 152,
    'grupo': 'Indep.',
    'code': 'INDO-CMX12-FV05028',
    'project': 'Jose A. Fndez - Paseo Reforma',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2019-05-09',
    'polEnd': '2024-11-09',
    'status': 'Vencida',
  },
  {
    'item': 153,
    'grupo': 'Indep.',
    'code': 'INDO-CMX13-FV05029',
    'project': 'Teresa segovia - Bosque de Pin',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2020-03-11',
    'polEnd': '2025-02-14',
    'status': 'Vencida',
  },
  {
    'item': 154,
    'grupo': 'Indep.',
    'code': 'INDO-HGO05-FV05030',
    'project': 'Casa Vaca - Amanali',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2024-01-25',
    'polEnd': '2025-01-24',
    'status': 'Vencida',
  },
  {
    'item': 155,
    'grupo': 'Indep.',
    'code': 'INDO-CMX14-FV05031',
    'project': 'Alejandro Chico - Tiro al Pichón',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2021-04-22',
    'polEnd': '2025-04-22',
    'status': 'Vencida',
  },
  {
    'item': 156,
    'grupo': 'Indep.',
    'code': 'INDO-CMX15-FV05032',
    'project': 'Mauricio Porraz - Cda Transmonte 609',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2021-06-09',
    'polEnd': '2025-03-22',
    'status': 'Vencida',
  },
  {
    'item': 157,
    'grupo': 'Indep.',
    'code': 'INDO-CMX16-FV05033',
    'project': 'Arcelia G Morton',
    'tarifa': 'DAC/01',
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 158,
    'grupo': 'Indep.',
    'code': 'INDO-CMX17-FV05034',
    'project': 'Azcarraga - Ahuehuetes Norte',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2019-10-23',
    'polEnd': '2021-10-23',
    'status': 'Vencida',
  },
  {
    'item': 159,
    'grupo': 'Indep.',
    'code': 'INDO-EDO08-FV05035',
    'project': 'Eduardo Arcila-Valle de Bravo',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2020-07-31',
    'polEnd': '2023-07-31',
    'status': 'Vencida',
  },
  {
    'item': 160,
    'grupo': 'Indep.',
    'code': 'INDO-CMX18-FV05036',
    'project': 'Claudia Monroy - Tiro al pichón 200',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2020-08-24',
    'polEnd': '2021-08-24',
    'status': 'Vencida',
  },
  {
    'item': 161,
    'grupo': 'Indep.',
    'code': 'INDO-CMX19-FV05037',
    'project': 'Guillermo Ballesteros',
    'tarifa': 'GDBT',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2021-02-15',
    'polEnd': '2022-02-15',
    'status': 'Vencida',
  },
  {
    'item': 162,
    'grupo': 'Indep.',
    'code': 'INDO-EDO09-FV05038',
    'project': 'Héctor Flores',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2021-04-15',
    'polEnd': '2022-10-15',
    'status': 'Vencida',
  },
  {
    'item': 163,
    'grupo': 'Indep.',
    'code': 'INDO-CMX20-FV05039',
    'project': 'Héctor Flores - Club de Golf SF',
    'tarifa': 'DAC/01',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2021-10-29',
    'polEnd': '2022-10-21',
    'status': 'Vencida',
  },
  {
    'item': 164,
    'grupo': 'Indep.',
    'code': 'INDO-CMX21-FV05040',
    'project': 'Beatriz Escobedo',
    'tarifa': 'DAC/01',
    'platform': 'EMA',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'COMPLETO',
    'polStart': '2021-11-04',
    'polEnd': '2024-02-16',
    'status': 'Vencida',
  },
  {
    'item': 165,
    'grupo': 'Indep.',
    'code': 'INDO-PUE02-FV05041',
    'project': 'Valentin Gary',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2020-04-20',
    'polEnd': '2021-04-20',
    'status': 'Vencida',
  },
  {
    'item': 166,
    'grupo': 'Indep.',
    'code': 'INDO-CMX22-FV05042',
    'project': 'Rosa Barrena',
    'tarifa': 'DAC/01',
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 167,
    'grupo': 'Indep.',
    'code': 'INDO-CMX23-FV05043',
    'project': 'Cheval',
    'tarifa': 'GDMTO',
    'platform': 'SunGrow',
    'sysStart': '2022-06-29',
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2022-06-29',
    'polEnd': '2024-06-29',
    'status': 'Vencida',
  },
  {
    'item': 168,
    'grupo': 'Indep.',
    'code': 'INDO-CMX24-FV05044',
    'project': 'Miguel Vives CDMX',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2020-01-03',
    'polEnd': '2021-01-03',
    'status': 'Vencida',
  },
  {
    'item': 169,
    'grupo': 'Indep.',
    'code': 'INDO-CMX25-FV05045',
    'project': 'Norma Salas',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2018-12-04',
    'polEnd': '2019-12-04',
    'status': 'Vencida',
  },
  {
    'item': 170,
    'grupo': 'Indep.',
    'code': 'INDO-YUC01-FV05046',
    'project': 'Guillermo Díaz Cocoyoles',
    'tarifa': 'DAC/01',
    'platform': 'Solaredge',
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2018-04-09',
    'polEnd': '2019-04-09',
    'status': 'Vencida',
  },
  {
    'item': 171,
    'grupo': 'Indep.',
    'code': 'INDO-CMX26-FV05047',
    'project': 'Sergio Cruz',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2019-02-18',
    'polEnd': '2020-02-18',
    'status': 'Vencida',
  },
  {
    'item': 172,
    'grupo': 'Indep.',
    'code': 'INDO-CMX27-FV05048',
    'project': 'Claudio Zapata',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2021-09-22',
    'polEnd': '2022-09-22',
    'status': 'Vencida',
  },
  {
    'item': 173,
    'grupo': 'Indep.',
    'code': 'INDO-GRO01-FV05049',
    'project': 'Paliza Acapulco',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2020-12-30',
    'polEnd': '2021-12-30',
    'status': 'Vencida',
  },
  {
    'item': 174,
    'grupo': 'Indep.',
    'code': 'INDO-EDO10-FV05050',
    'project': 'Manuel Pacheco',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': None,
    'poliza': 'INCIDENCIAS FULL',
    'polStart': '2020-05-01',
    'polEnd': '2021-05-01',
    'status': 'Vencida',
  },
  {
    'item': 175,
    'grupo': 'Indep.',
    'code': 'INDO-GDL01-FV05051',
    'project': 'Punta Mita (Four Seasons)',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': None,
    'zona': 'Guadalajara',
    'cuadrilla': 'Especial',
    'poliza': 'ELÉCTRICO',
    'polStart': '2025-11-25',
    'polEnd': '2026-11-25',
    'status': 'Vigente',
  },
  {
    'item': 176,
    'grupo': 'Indep.',
    'code': 'INDO-MOR01-FV05052',
    'project': 'Juan Carlos Hernaiz Cuernavaca',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2018-06-14',
    'polEnd': '2019-06-13',
    'status': 'Vencida',
  },
  {
    'item': 177,
    'grupo': 'Indep.',
    'code': 'INDO-MLM01-FV05053',
    'project': 'CAMUCUATO',
    'tarifa': 'GDMTH',
    'platform': 'EnnexOS',
    'sysStart': '2020-04-16',
    'zona': 'Michoacán',
    'cuadrilla': None,
    'poliza': 'FINALIZADO',
    'polStart': '2020-04-16',
    'polEnd': '2021-04-16',
    'status': 'Vencida',
  },
  {
    'item': 178,
    'grupo': 'Indep.',
    'code': 'INDO-EDO11-FV05054',
    'project': 'MERCK',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2024-02-02',
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': '2 completos, 2 limpiezas',
    'polStart': '2024-02-02',
    'polEnd': '2026-02-02',
    'status': 'Vencida',
  },
  {
    'item': 179,
    'grupo': 'Indep.',
    'code': 'INDO-VER01-FV05055',
    'project': 'Nuvoil Grande',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2023-11-24',
    'zona': 'Veracruz',
    'cuadrilla': 'Proveedor',
    'poliza': 'COMPLETO',
    'polStart': '2023-11-24',
    'polEnd': '2024-11-24',
    'status': 'Vencida',
  },
  {
    'item': 180,
    'grupo': 'Indep.',
    'code': 'INDO-VER02-FV05056',
    'project': 'Nuvoil Chico',
    'tarifa': 'GDMTO',
    'platform': 'Solis',
    'sysStart': '2023-06-23',
    'zona': 'Veracruz',
    'cuadrilla': 'Proveedor',
    'poliza': 'COMPLETO',
    'polStart': '2023-06-23',
    'polEnd': '2024-06-23',
    'status': 'Vencida',
  },
  {
    'item': 181,
    'grupo': 'Indep.',
    'code': 'INDO-HGO06-HB05057',
    'project': 'FRITOS TOTIS',
    'tarifa': None,
    'platform': None,
    'sysStart': '2025-05-02',
    'zona': 'Estado de México',
    'cuadrilla': 'Tizayuca',
    'poliza': 'COMPLETO',
    'polStart': '2024-09-11',
    'polEnd': '2026-09-11',
    'status': 'Vigente',
  },
  {
    'item': 182,
    'grupo': 'Indep.',
    'code': 'INDO-CMX28-BT05058',
    'project': 'BROM',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 183,
    'grupo': 'Indep.',
    'code': 'INDO-EDO12-BT05059',
    'project': 'UNIDOC',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 184,
    'grupo': 'Indep.',
    'code': 'INDO-CUU03-BT05060',
    'project': 'RESIDEO',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': None,
    'cuadrilla': 'Especial',
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 185,
    'grupo': 'Indep.',
    'code': 'INDO-CMX39-FV05061',
    'project': 'JJ Risoul - Sistema Risco 431',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2017-10-12',
    'polEnd': '2018-10-12',
    'status': 'Vencida',
  },
  {
    'item': 186,
    'grupo': 'Indep.',
    'code': 'INDO-CMX40-FV05062',
    'project': 'Julio Kuri-Tlapexco 203',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2022-10-04',
    'polEnd': '2023-10-05',
    'status': 'Vencida',
  },
  {
    'item': 187,
    'grupo': 'Indep.',
    'code': 'INDO-EDO22-FV05063',
    'project': 'Aerobal',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2021-12-29',
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2021-12-29',
    'polEnd': '2023-12-31',
    'status': 'Vencida',
  },
  {
    'item': 188,
    'grupo': 'Indep.',
    'code': 'INDO-GDL03-FV05064',
    'project': 'Plaza Sania',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': '2021-03-08',
    'zona': 'Guadalajara',
    'cuadrilla': 'Especial',
    'poliza': 'FINALIZADO',
    'polStart': '2021-03-08',
    'polEnd': '2023-02-05',
    'status': 'Vencida',
  },
  {
    'item': 189,
    'grupo': 'Indep.',
    'code': 'INDO-QRO03-FV05065',
    'project': 'EL PALACIO DE HIERRO QRO',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2025-07-01',
    'zona': 'Querétaro',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2025-07-01',
    'polEnd': '2027-07-01',
    'status': 'Vigente',
  },
  {
    'item': 190,
    'grupo': 'Indep.',
    'code': 'INDO-HGO11-FV05066',
    'project': 'METALITEC',
    'tarifa': 'GDMTH',
    'platform': 'EnnexOS',
    'sysStart': '2018-10-30',
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'FINALIZADO',
    'polStart': '2018-10-30',
    'polEnd': '2019-10-30',
    'status': 'Vencida',
  },
  {
    'item': 191,
    'grupo': 'Indep.',
    'code': 'INDO-HGO12-FV05067',
    'project': 'INECUH',
    'tarifa': 'GDMTO',
    'platform': 'Solis',
    'sysStart': '2022-03-14',
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'FINALIZADO',
    'polStart': '2022-03-14',
    'polEnd': '2024-03-14',
    'status': 'Vencida',
  },
  {
    'item': 192,
    'grupo': 'Indep.',
    'code': 'INDO-HGO13-FV05068',
    'project': 'Luisa Riba',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': None,
    'cuadrilla': 'Tizayuca',
    'poliza': 'FINALIZADO',
    'polStart': '2020-11-06',
    'polEnd': '2021-11-06',
    'status': 'Vencida',
  },
  {
    'item': 193,
    'grupo': 'Indep.',
    'code': 'INDO-HGO14-FV05069',
    'project': 'Cilindros Meba',
    'tarifa': 'GDMTH',
    'platform': 'SunGrow',
    'sysStart': '2022-06-07',
    'zona': 'Hidalgo',
    'cuadrilla': 'Tizayuca',
    'poliza': 'FINALIZADO',
    'polStart': '2022-06-07',
    'polEnd': '2023-06-07',
    'status': 'Vencida',
  },
  {
    'item': 194,
    'grupo': 'Indep.',
    'code': 'INDO-CMX41-FV05070',
    'project': 'Altadena',
    'tarifa': 'PDBT',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 195,
    'grupo': 'Indep.',
    'code': 'INDO-CMX42-FV05071',
    'project': 'Antara',
    'tarifa': 'GDMTH',
    'platform': 'EnnexOS',
    'sysStart': '2019-04-26',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2019-04-26',
    'polEnd': '2026-04-26',
    'status': 'Vencida',
  },
  {
    'item': 196,
    'grupo': 'Indep.',
    'code': 'INDO-CMX43-FV05072',
    'project': 'Pablo Favela - Carrizal',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2020-09-25',
    'polEnd': '2023-10-31',
    'status': 'Vencida',
  },
  {
    'item': 197,
    'grupo': 'Indep.',
    'code': 'INDO-EDO23-FV05073',
    'project': 'Pablo Favela - Carrizal 30D',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2020-10-28',
    'polEnd': '2023-10-31',
    'status': 'Vencida',
  },
  {
    'item': 198,
    'grupo': 'Indep.',
    'code': 'INDO-MOR02-FV05074',
    'project': 'Pablo Favela - Piamonte 1',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2021-04-26',
    'polEnd': '2023-10-31',
    'status': 'Vencida',
  },
  {
    'item': 199,
    'grupo': 'Indep.',
    'code': 'INDO-QRO04-FV05075',
    'project': 'TRIMEX LARRY',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Queretaro',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2025-07-01',
    'polEnd': '2026-07-01',
    'status': 'Vigente',
  },
  {
    'item': 200,
    'grupo': 'Indep.',
    'code': 'INDO-AGS03-FV05076',
    'project': 'PLAZA UNIVERSIDAD AC 2',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Aguascalientes',
    'cuadrilla': 'Especial',
    'poliza': 'FINALIZADO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 201,
    'grupo': 'Indep.',
    'code': 'INDO-AGS04-FV05077',
    'project': 'PLAZA UNIVERSIDAD AC 3',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Aguascalientes',
    'cuadrilla': 'Especial',
    'poliza': 'FINALIZADO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 202,
    'grupo': 'Indep.',
    'code': 'INDO-CRI01-FV05078',
    'project': 'HOLOGIC COSTA RICA',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Costa Rica',
    'cuadrilla': 'Especial',
    'poliza': '1 completo, \n1 eléctrico',
    'polStart': '2025-05-11',
    'polEnd': '2026-05-11',
    'status': 'Vencida',
  },
  {
    'item': 203,
    'grupo': 'Indep.',
    'code': 'INDO-CMX48-FV05079',
    'project': 'ECOFRIO P14',
    'tarifa': None,
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONTRATO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 204,
    'grupo': 'Indep.',
    'code': 'INDO-AGS05-BT05080',
    'project': 'IPASA',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2025-06-28',
    'zona': 'Aguascalientes',
    'cuadrilla': 'Especial',
    'poliza': 'REVISAR',
    'polStart': '2025-06-28',
    'polEnd': '2026-06-28',
    'status': 'Vigente',
  },
  {
    'item': 205,
    'grupo': 'Indep.',
    'code': 'INDO-CMX49-FV05081',
    'project': 'Telas Bayon',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2023-07-26',
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2023-07-06',
    'polEnd': '2024-07-06',
    'status': 'Vencida',
  },
  {
    'item': 206,
    'grupo': 'Indep.',
    'code': 'INDO-AGS06-FV05082',
    'project': 'PLAZA UNIVERSIDAD AC',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Aguascalientes',
    'cuadrilla': 'Especial',
    'poliza': 'FINALIZADO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 207,
    'grupo': 'Indep.',
    'code': 'INDO-EDO33-FV05083',
    'project': 'La Gavia',
    'tarifa': 'GDMTO',
    'platform': 'SunGrow',
    'sysStart': '2021-11-29',
    'zona': 'Estado de México',
    'cuadrilla': 'Especial',
    'poliza': 'ELÉCTRICO',
    'polStart': '2021-11-29',
    'polEnd': '2022-11-29',
    'status': 'Vencida',
  },
  {
    'item': 208,
    'grupo': 'Indep.',
    'code': 'INDO-EDO34-FV05084',
    'project': 'La Katira',
    'tarifa': 'GDMTO',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Especial',
    'poliza': 'FINALIZADO',
    'polStart': '2022-04-22',
    'polEnd': '2023-04-22',
    'status': 'Vencida',
  },
  {
    'item': 209,
    'grupo': 'Indep.',
    'code': 'INDO-CMX51-FV05085',
    'project': 'David Chelminsky - Lomas Altas',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2023-01-10',
    'polEnd': '2023-08-26',
    'status': 'Vencida',
  },
  {
    'item': 210,
    'grupo': 'Indep.',
    'code': 'INDO-CMX52-FV05086',
    'project': 'Sanchez Aedo Sierra Paracaima',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2023-07-18',
    'polEnd': '2024-07-18',
    'status': 'Vencida',
  },
  {
    'item': 211,
    'grupo': 'Indep.',
    'code': 'INDO-CMX53-FV05087',
    'project': 'Gerardo Tinoco -Calle José de Teresa',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2021-01-22',
    'polEnd': '2022-01-22',
    'status': 'Vencida',
  },
  {
    'item': 212,
    'grupo': 'Indep.',
    'code': 'INDO-CMX54-FV05088',
    'project': 'Microsoft',
    'tarifa': 'GDMTH',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2019-04-26',
    'polEnd': '2020-04-26',
    'status': 'Vencida',
  },
  {
    'item': 213,
    'grupo': 'Indep.',
    'code': 'INDO-QRO05-FV05089',
    'project': 'Antea I',
    'tarifa': None,
    'platform': 'SunGrow',
    'sysStart': None,
    'zona': 'Querétaro',
    'cuadrilla': 'Especial',
    'poliza': 'COMPLETO',
    'polStart': '2026-01-01',
    'polEnd': '2029-01-01',
    'status': 'Vigente',
  },
  {
    'item': 214,
    'grupo': 'Indep.',
    'code': 'INDO-EDO35-FV05090',
    'project': 'Jorge Lopez - Metepec',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2019-06-27',
    'polEnd': '2020-06-27',
    'status': 'Vencida',
  },
  {
    'item': 215,
    'grupo': 'Indep.',
    'code': 'INDO-YUC19-FV05091',
    'project': 'José Luis Rodriguez',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Yucatán',
    'cuadrilla': 'Península',
    'poliza': 'FINALIZADO',
    'polStart': '2020-11-26',
    'polEnd': '2021-11-26',
    'status': 'Vencida',
  },
  {
    'item': 216,
    'grupo': 'Indep.',
    'code': 'INDO-CMX55-FV05092',
    'project': 'Gloria Treviño - Monte de Saja',
    'tarifa': 'DAC/01',
    'platform': 'EnnexOS',
    'sysStart': None,
    'zona': 'Ciudad de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'FINALIZADO',
    'polStart': '2020-10-20',
    'polEnd': '2021-10-20',
    'status': 'Vencida',
  },
  {
    'item': 217,
    'grupo': 'Indep.',
    'code': 'INDO-MOR03-FV05094',
    'project': 'Diego Cabrero - Tabachines 188',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'Cuernavaca',
    'cuadrilla': 'Especial',
    'poliza': 'FINALIZADO',
    'polStart': '2018-10-23',
    'polEnd': '2022-09-01',
    'status': 'Vencida',
  },
  {
    'item': 218,
    'grupo': 'Indep.',
    'code': 'F.C. 1',
    'project': 'BOLSAS ARTESANALES 1',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 219,
    'grupo': 'Indep.',
    'code': 'INDO-EDO41-FV05106',
    'project': 'BIDASOA',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 220,
    'grupo': 'Indep.',
    'code': 'F.C. 3',
    'project': 'CLARINORIT',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': 'Coahuila',
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 221,
    'grupo': 'Indep.',
    'code': 'F.C. 4',
    'project': 'TEXTURIZADOS',
    'tarifa': 'GDMTH',
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 222,
    'grupo': 'Indep.',
    'code': 'F.C. 5',
    'project': 'CODIGO FOODS',
    'tarifa': 'GDMTH',
    'platform': None,
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 223,
    'grupo': 'Indep.',
    'code': 'F.C. 6',
    'project': 'BOLSAS ARTESANALES 2',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 224,
    'grupo': 'Indep.',
    'code': 'F.C. 7',
    'project': 'BOLSAS ARTESANALES 3',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 225,
    'grupo': 'Indep.',
    'code': 'F.C. 8',
    'project': 'DULCES MODELO 1',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 226,
    'grupo': 'Indep.',
    'code': 'F.C. 9',
    'project': 'DULCES MODELO 2',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 227,
    'grupo': 'Indep.',
    'code': 'F.C. 10',
    'project': 'CREDICER',
    'tarifa': 'GDMTH',
    'platform': None,
    'sysStart': None,
    'zona': 'León',
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 228,
    'grupo': 'Indep.',
    'code': 'F.C. 11',
    'project': 'BODESA - Villa de Álvarez',
    'tarifa': 'GDMTH',
    'platform': None,
    'sysStart': None,
    'zona': 'Colima',
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 229,
    'grupo': 'Indep.',
    'code': 'F.C. 12',
    'project': 'BODESA - Zamora',
    'tarifa': 'GDMTO',
    'platform': None,
    'sysStart': None,
    'zona': 'Michoacán',
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 230,
    'grupo': 'Indep.',
    'code': 'F.C. 13',
    'project': 'BODESA - Medellín 77',
    'tarifa': 'GDMTO',
    'platform': None,
    'sysStart': None,
    'zona': 'Colima',
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 231,
    'grupo': 'Indep.',
    'code': 'F.C. 14',
    'project': 'BODESA - El Porvenir',
    'tarifa': 'GDMTO',
    'platform': None,
    'sysStart': None,
    'zona': 'Colima',
    'cuadrilla': None,
    'poliza': 'CONSTRUCCIÓN',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 232,
    'grupo': 'Indep.',
    'code': 'INDO-CMX56-FV05095',
    'project': 'Fernanda Rivero_ fuente del pescador 197_MEX',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'X VISITA',
    'polStart': '2020-10-07',
    'polEnd': '2021-10-07',
    'status': 'Vencida',
  },
  {
    'item': 233,
    'grupo': 'Indep.',
    'code': 'INDO-EDO36-FV05097',
    'project': 'Sofía Perochena - Calle del parque 30',
    'tarifa': 'DAC/01',
    'platform': 'Solis',
    'sysStart': '2020-06-16',
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2020-06-16',
    'polEnd': '2021-06-16',
    'status': 'Vencida',
  },
  {
    'item': 234,
    'grupo': 'Indep.',
    'code': 'INDO-GTO03-FV05104',
    'project': 'AGROBAL ESTABLO',
    'tarifa': 'GDMTO',
    'platform': 'Solis',
    'sysStart': '2026-02-18',
    'zona': 'Guanajuato',
    'cuadrilla': 'Especial',
    'poliza': 'Sin póliza, Inc. Full',
    'polStart': '2026-02-18',
    'polEnd': '2027-02-18',
    'status': 'Vigente',
  },
  {
    'item': 235,
    'grupo': 'Indep.',
    'code': 'INDO-GTO04-FV05105',
    'project': 'AGROBAL ORDEÑA',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': '2026-02-18',
    'zona': 'Guanajuato',
    'cuadrilla': 'Especial',
    'poliza': 'Sin póliza, Inc. Full',
    'polStart': '2026-02-18',
    'polEnd': '2027-02-18',
    'status': 'Vigente',
  },
  {
    'item': 236,
    'grupo': None,
    'code': 'INDO-EDO38-FV05100',
    'project': 'Emergent Cold P18-101',
    'tarifa': None,
    'platform': 'Solis',
    'sysStart': None,
    'zona': None,
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONTRATO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 237,
    'grupo': None,
    'code': 'INDO-EDO39-FV05101',
    'project': 'Emergent Cold P18-212',
    'tarifa': None,
    'platform': 'Solis',
    'sysStart': None,
    'zona': None,
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONTRATO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 238,
    'grupo': None,
    'code': 'INDO-EDO40-FV05102',
    'project': 'Emergent Cold P18-327',
    'tarifa': None,
    'platform': 'Solis',
    'sysStart': None,
    'zona': None,
    'cuadrilla': 'Metropolitana',
    'poliza': 'CONTRATO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 239,
    'grupo': None,
    'code': None,
    'project': 'Colosio, Aguascalientes',
    'tarifa': None,
    'platform': 'Fusion Solar',
    'sysStart': '2025-03-06',
    'zona': 'Aguascalientes',
    'cuadrilla': 'Especial',
    'poliza': 'CONTRATO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 240,
    'grupo': None,
    'code': None,
    'project': 'Chedraui, Ixtepec',
    'tarifa': None,
    'platform': 'Fusion Solar',
    'sysStart': '2025-05-09',
    'zona': 'Oaxaca',
    'cuadrilla': 'Especial',
    'poliza': 'CONTRATO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 241,
    'grupo': None,
    'code': None,
    'project': 'Chedraui, Cunduacan',
    'tarifa': None,
    'platform': 'Fusion Solar',
    'sysStart': '2025-05-21',
    'zona': 'Tabasco',
    'cuadrilla': 'Especial',
    'poliza': 'CONTRATO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': 242,
    'grupo': None,
    'code': None,
    'project': 'MPI Products',
    'tarifa': None,
    'platform': None,
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': 'COMPLETO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': None,
    'grupo': None,
    'code': 'INDO-EDO42-FV05108',
    'project': 'Acrílicos Sablón',
    'tarifa': 'GDMTH',
    'platform': 'Solis',
    'sysStart': None,
    'zona': None,
    'cuadrilla': None,
    'poliza': None,
    'polStart': '2023-09-27',
    'polEnd': '2024-09-27',
    'status': 'Vencida',
  },
  {
    'item': None,
    'grupo': None,
    'code': 'INDO-EDO37-HB05098',
    'project': 'Tejidos y Texturizados',
    'tarifa': None,
    'platform': 'Fusion Solar',
    'sysStart': None,
    'zona': 'Estado de México',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': None,
    'polEnd': None,
    'status': None,
  },
  {
    'item': None,
    'grupo': None,
    'code': 'INDO-CMX57-FV05099',
    'project': 'Eurovalle',
    'tarifa': 'GDBT',
    'platform': 'Solis',
    'sysStart': None,
    'zona': 'CDMX',
    'cuadrilla': 'Metropolitana',
    'poliza': 'COMPLETO',
    'polStart': '2022-03-24',
    'polEnd': '2024-03-24',
    'status': 'Vencida',
  },
]
